name: telogator2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - biopython>=1.82
  - muscle=3.8
  - matplotlib
  - numpy
  - scipy
  - pysam
  - regex
  - pywavelets
